# -*- coding: utf-8 -*-
"""preprocessing_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZJZOrUqZaq7M57oTGw-pL8Dbpf6RZlo

# Preprocessing Notebook
Chay tuan tu tung cell.

## CELL 1 – Cài thư viện & mount Drive
"""

# !pip install groq -q

from google.colab import drive
drive.mount('/content/drive')

!pip install groq -q
import pandas as pd
import numpy as np
import re, json, os, time
from groq import Groq

GROQ_API_KEY = ""
DATA_PATH    = "/content/drive/Shareddrives/KTV/KIẾN TẬP/Data/data_final_raw.csv"
OUTPUT_DIR   = "/content/drive/Shareddrives/KTV/KIẾN TẬP/Data/output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(" Setup xong")

"""## CELL 2 – Load data"""

df = pd.read_csv(DATA_PATH)

print(f"Shape   : {df.shape[0]:,} dòng × {df.shape[1]} cột")
print(f"Columns : {list(df.columns)}")
print(f"Tổng NaN: {df.isna().sum().sum():,}")
print()
print("Preview 5 dòng")
print(df.head())

"""## CELL 3 – Datetime conversion (theo format thực tế từng source)"""

#   homedy       : YYYY-MM-DD
#   nhadatcanban : M/D/YYYY  (US, tháng/ngày/năm)
#   batdongsan   : mixed (chưa có data để xác nhận)
DATE_COLS = ["posted_at", "expired_at", "snapshot_date"]

# homedy → YYYY-MM-DD
mask = df["source_name"] == "homedy"
for col in DATE_COLS:
    if col in df.columns:
        df.loc[mask, col] = pd.to_datetime(df.loc[mask, col], format="%Y-%m-%d", errors="coerce")

# nhadatcanban → M/D/YYYY
mask = df["source_name"] == "nhadatcanban"
for col in ["posted_at", "snapshot_date"]:
    if col in df.columns:
        df.loc[mask, col] = pd.to_datetime(df.loc[mask, col], format="%m/%d/%Y", errors="coerce")

# batdongsan.com → mixed (update format khi có data thực tế)
mask = df["source_name"] == "batdongsan.com"
for col in DATE_COLS:
    if col in df.columns:
        df.loc[mask, col] = pd.to_datetime(df.loc[mask, col], format="mixed", dayfirst=True, errors="coerce")

# Source khác → mixed
known = {"batdongsan.com", "homedy", "nhadatcanban"}
mask = ~df["source_name"].isin(known)
if mask.any():
    for col in DATE_COLS:
        if col in df.columns:
            df.loc[mask, col] = pd.to_datetime(df.loc[mask, col], format="mixed", errors="coerce")

# Ép lại toàn bộ → datetime64 thống nhất
for col in DATE_COLS:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], format="mixed", errors="coerce")

# Kết quả
print(" KẾT QUẢ – Datetime Conversion")
print(f"{'Cột':<22} {'Dtype':<18} {'NaT':>8} {'%NaT':>7}")
print("-" * 58)
for col in DATE_COLS:
    if col in df.columns:
        n   = df[col].isna().sum()
        pct = n / len(df) * 100
        ok  = "" if "datetime" in str(df[col].dtype) else ""
        print(f"{col:<22} {str(df[col].dtype):<18} {n:>8,} {pct:>6.1f}%  {ok}")

print("\nNaT theo từng source:")
for col in DATE_COLS:
    if col in df.columns:
        print(f"\n  [{col}]")
        breakdown = df.groupby("source_name")[col].apply(lambda x: x.isna().sum())
        for src, n in breakdown.items():
            pct = n / df[df["source_name"]==src].shape[0] * 100
            flag = "  " if pct > 5 else ""
            print(f"    {src:<25} NaT={n:>5,} ({pct:.1f}%){flag}")

print("\nMẫu dữ liệu sau parse:")
for src in df["source_name"].unique():
    print(f"\n  [{src}]")
    print(df[df["source_name"]==src][DATE_COLS].dropna(how="all").head(3).to_string())

"""CELL 4 – Fix format & đổi kiểu dữ liệu"""

PLACEHOLDER = {"", "n/a", "na", "none", "null", "không có", "không", "-", "--", "?"}

def clean_str(val):
    if pd.isna(val): return val
    s = str(val).strip()
    return np.nan if s.lower() in PLACEHOLDER else s

# Trim placeholder toàn bộ object cols
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].apply(clean_str)

INT_COLS   = ["bedrooms","bathrooms","source_listing_id","num_towers",
              "total_apartment","launch_year","handover_year"]
FLOAT_COLS = ["area_m2","price_total_vnd","price_per_m2_vnd","land_area_ha",
              "construction_density","dist_cbd_km","dist_metro_km",
              "dist_river_lake_km","dist_highway_km","dist_airport_km",
              "dist_market","dist_school","dist_park","dist_hospital"]
HAS_COLS   = [c for c in df.columns if c.startswith("has_")]

dtype_log = []   # ghi lại thay đổi để in

for col in INT_COLS:
    if col in df.columns:
        before = str(df[col].dtype)
        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
        dtype_log.append((col, before, "Int64", df[col].isna().sum()))

for col in FLOAT_COLS:
    if col in df.columns:
        before = str(df[col].dtype)
        df[col] = pd.to_numeric(df[col], errors="coerce")
        dtype_log.append((col, before, "float64", df[col].isna().sum()))

for col in HAS_COLS:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
        dtype_log.append((col, "object", "int(0/1)", df[col].isna().sum()))

# --- Kết quả ---
print(" KẾT QUẢ – Fix Format & Dtype")
print(f"{'Cột':<30} {'Trước':>10} {'Sau':>10} {'NaN':>8}")
print("-" * 62)
for col, b, a, nan in dtype_log:
    print(f"{col:<30} {b:>10} {a:>10} {nan:>8,}")
print(f"\nTổng NaN toàn df: {df.isna().sum().sum():,}")

"""CELL 5 – Remove duplicates"""

before = len(df)

df.drop_duplicates(keep="first", inplace=True)
after_exact = len(df)

if "source_listing_id" in df.columns and "source_name" in df.columns:
    if "snapshot_date" in df.columns:
        df.sort_values("snapshot_date", ascending=False, inplace=True)
    df.drop_duplicates(subset=["source_listing_id","source_name"], keep="first", inplace=True)

df.reset_index(drop=True, inplace=True)
after_biz = len(df)

# Ket qua tong hop
print("KET QUA - Remove Duplicates")
print(f"{'':30} {'Dong':>8}")
print("-" * 40)
print(f"{'Truoc':<30} {before:>8,}")
print(f"{'Xoa exact duplicate':<30} {before - after_exact:>8,}")
print(f"{'Xoa business duplicate':<30} {after_exact - after_biz:>8,}")
print(f"{'Con lai':<30} {after_biz:>8,}  ({after_biz/before*100:.1f}% giu lai)")

# Unique values tung cot
print()
print("UNIQUE VALUES TUNG COT SAU KHI DEDUP")
print("=" * 60)
print(f"{'Cot':<35} {'Unique':>8} {'NaN':>8} {'% NaN':>8}")
print("-" * 60)
for col in df.columns:
    n_unique = df[col].nunique(dropna=True)
    n_nan    = df[col].isna().sum()
    pct_nan  = n_nan / len(df) * 100
    print(f"{col:<35} {n_unique:>8,} {n_nan:>8,} {pct_nan:>7.1f}%")

# Chi tiet cac cot phan loai (unique <= 30)
print()
print("CHI TIET GIA TRI - COT PHAN LOAI (unique <= 30)")
print("=" * 60)
cat_cols = [c for c in df.columns if df[c].nunique(dropna=True) <= 30]
for col in cat_cols:
    print(f"\n  [{col}]")
    vc = df[col].value_counts(dropna=False)
    for val, cnt in vc.items():
        pct   = cnt / len(df) * 100
        label = "(NaN)" if pd.isna(val) else str(val)
        print(f"    {label:<30} {cnt:>7,}  ({pct:.1f}%)")

"""## CELL 6 – Handle missing obvious"""

total_before = df.isna().sum().sum()
fill_log = []

# has_* → 0
for col in [c for c in df.columns if c.startswith("has_")]:
    n = df[col].isna().sum()
    if n > 0:
        df[col] = df[col].fillna(0).astype(int)
        fill_log.append((col, n, 0, "fillna(0)"))

# Outlier → NaN
outlier_rules = {
    "bedrooms"       : (1, 20),
    "bathrooms"      : (1, 20),
    "area_m2"        : (5, 10000),
    "price_total_vnd": (1e7, 1e13),
}
for col, (lo, hi) in outlier_rules.items():
    if col in df.columns:
        mask = df[col].notna() & ((df[col] < lo) | (df[col] > hi))
        if mask.any():
            df.loc[mask, col] = np.nan
            fill_log.append((col, mask.sum(), df[col].isna().sum(), f"outlier → NaN [{lo},{hi}]"))

# Text cols → ""
for col in ["title", "listing_description", "address"]:
    if col in df.columns:
        n = df[col].isna().sum()
        if n > 0:
            df[col] = df[col].fillna("")
            fill_log.append((col, n, 0, 'fillna("")'))

total_after = df.isna().sum().sum()

# --- Kết quả ---
print(" KẾT QUẢ – Handle Missing Obvious")
print(f"{'Cột':<30} {'Xử lý':>8} {'Action':<25}")
print("-" * 65)
for col, changed, remaining, action in fill_log:
    print(f"{col:<30} {changed:>8,}  {action:<25}")
print(f"\nTổng NaN: {total_before:,} → {total_after:,}  (giảm {total_before - total_after:,})")

remaining_nan = df.isna().sum()
remaining_nan = remaining_nan[remaining_nan > 0].sort_values(ascending=False)
if not remaining_nan.empty:
    print(f"\nMissing còn lại:")
    print(f"{'Cột':<35} {'NaN':>8} {'%':>7}")
    print("-" * 52)
    for col, n in remaining_nan.items():
        print(f"{col:<35} {n:>8,} {n/len(df)*100:>6.1f}%")

"""## CELL 7 – Rule-based normalization"""

VALID_DIRECTION = ["Đông-Nam","Đông-Bắc","Tây-Nam","Tây-Bắc","Đông","Tây","Nam","Bắc","Chưa rõ"]
VALID_LEGAL     = ["Sổ hồng/Sổ đỏ","Hợp đồng mua bán","Chưa rõ"]
VALID_FURNITURE = ["Đầy đủ","Cơ bản","Không nội thất","Chưa rõ"]
COL_PAIRS       = [("direction_norm","direction"),
                   ("legal_status_norm","legal_status"),
                   ("furniture_status_norm","furniture_status")]

def rule_direction(val):
    if pd.isna(val) or str(val).strip() == "":
        return None

    # Buoc 1: chuan hoa khoang trang va dau gan het
    v = str(val).strip()
    v = re.sub(r"\s*[-–−]\s*", "-", v)   # "Đông - Nam", "Đông– Nam" → "Đông-Nam"
    v = re.sub(r"\s+", "-", v)           # "Đông Nam" → "Đông-Nam"
    v = v.lower()

    DIRECTION_MAP = {
        # Đông-Nam (tat ca bien the sau khi chuan hoa deu thanh "đông-nam")
        "đông-nam"  : "Đông-Nam",
        "dong-nam"  : "Đông-Nam",
        "dn"        : "Đông-Nam",

        # Đông-Bắc
        "đông-bắc"  : "Đông-Bắc",
        "dong-bac"  : "Đông-Bắc",
        "db"        : "Đông-Bắc",

        # Tây-Nam
        "tây-nam"   : "Tây-Nam",
        "tay-nam"   : "Tây-Nam",
        "tn"        : "Tây-Nam",

        # Tây-Bắc
        "tây-bắc"   : "Tây-Bắc",
        "tay-bac"   : "Tây-Bắc",
        "tb"        : "Tây-Bắc",

        # Don
        "đông"      : "Đông",
        "dong"      : "Đông",
        "tây"       : "Tây",
        "tay"       : "Tây",
        "nam"       : "Nam",
        "bắc"       : "Bắc",
        "bac"       : "Bắc",
    }

    # Exact match
    if v in DIRECTION_MAP:
        return DIRECTION_MAP[v]

    # Contains match: dai → ngan
    for key in sorted(DIRECTION_MAP, key=len, reverse=True):
        if key in v:
            return DIRECTION_MAP[key]

    return None

df["direction_norm"] = df["direction"].apply(rule_direction)

def rule_legal(val):
    if pd.isna(val) or str(val).strip() == "":
        return None

    v = str(val).strip().lower()
    # Chuan hoa: bo dau cham cuoi, khoang trang thua
    v = re.sub(r"\s+", " ", v).strip(" .")

    # So hong / So do
    SO_HONG_KEYWORDS = [
        "sổ hồng", "sổ đỏ", "so hong", "so do", "shr", "sđr",
        "có sổ", "đã có sổ", "sổ sẵn", "sẵn sổ", "sổ cá nhân",
        "sổ công ty", "sổ cđt", "pháp lý: sổ", "sổ hồng lâu dài",
        "sổ hồng vĩnh viễn", "sở hữu lâu dài", "sở hữu vĩnh viễn",
        "vĩnh viễn", "sổ chính chủ", "đang làm sổ", "đang chờ sổ",
        "sắp có sổ", "đã nộp hồ sơ làm sổ", "đã có thông báo làm sổ",
        "spa",           # SPA - nguoi nuoc ngoai so huu
        "gpxd",          # giay phap xay dung
        "giấy tờ hợp lệ", "giấy tờ khác", "pháp lý đầy đủ",
        "pháp lý rõ ràng", "pháp lí rõ ràng", "pháp lý chuẩn",
        "pháp lý minh bạch",
    ]

    # Hop dong mua ban
    HDMB_KEYWORDS = [
        "hợp đồng mua bán", "hđmb", "hdmb", "hop dong mua ban",
        "hợp đồng chuyển nhượng", "chuyển nhượng hợp đồng",
        "hợp đồng mua bán sở hữu",
        "ký hợp đồng mua bán",       # Vinhomes HDMB
        "văn bản thỏa thuận", "văn bản thoả thuận",  # van ban = truoc HDMB
        "van ban thoa thuan",
    ]

    # ── Hop dong dat coc
    HDDC_KEYWORDS = [
        "hợp đồng đặt cọc", "hợp đồng cọc", "hđđc", "hddc",
        "chờ hdmb", "chờ hđmb",
    ]

    #Hop dong thue
    HOPT_KEYWORDS = [
        "hợp đồng thuê", "hợp đồng cho thuê", "hop dong cho thue",
        "đang có hđ thuê", "hợp đồng thuê dài hạn",
    ]

    #Hop dong khac (chi "Hop dong" chung chung)
    HD_KEYWORDS = [
        "hợp đồng", "hop dong",
    ]

    #Lien he (khong ro phap ly)
    LIENHE_KEYWORDS = ["liên hệ"]

    # Check theo thu tu uu tien: cu the → chung chung
    if any(k in v for k in SO_HONG_KEYWORDS):
        return "Sổ hồng/Sổ đỏ"
    if any(k in v for k in HDMB_KEYWORDS):
        return "Hợp đồng mua bán"
    if any(k in v for k in HDDC_KEYWORDS):
        return "Hợp đồng mua bán"   # gom vao HDMB vi cung la dang giao dich
    if any(k in v for k in HOPT_KEYWORDS):
        return None                  # hop dong thue → groq xu ly
    if any(k in v for k in HD_KEYWORDS):
        return "Hợp đồng mua bán"
    if any(k in v for k in LIENHE_KEYWORDS):
        return None                  # "Lien he" = khong biet → groq

    return None


df["legal_status_norm"] = df["legal_status"].apply(rule_legal)

# Ket qua
total = len(df)
identified = df["legal_status_norm"].notna().sum()
need_groq  = df["legal_status_norm"].isna().sum()

print("KET QUA - Rule-based legal_status_norm")
print(f"{'Rule xac dinh':<25} {identified:>7,}  ({identified/total*100:.1f}%)")
print(f"{'None → giao Groq':<25} {need_groq:>7,}  ({need_groq/total*100:.1f}%)")
print()
print(f"{'Nhan':<25} {'Dong':>8} {'%':>7}")
print("-" * 42)
for lbl, cnt in df["legal_status_norm"].value_counts(dropna=False).items():
    label = "(None → Groq)" if pd.isna(lbl) else str(lbl)
    print(f"{label:<25} {cnt:>8,} {cnt/total*100:>6.1f}%)")

def rule_furniture(val):
    if pd.isna(val) or str(val).strip() == "":
        return None
    v = re.sub(r"\s+", " ", str(val).strip().lower()).strip(" .")

    KHONG_NT = ["không nội thất","không có nội thất","bàn giao thô",
                "bàn giao trống","bàn giao nhà thô","bàn giao nhà trống",
                "giao thô","nhà thô","nhà trống","trống","thô","đất trống",
                "penthouse bàn giao thô","ban giao"]
    DAY_DU   = ["cao cấp","noi that cao cap","nội thất cao cấp",
                "full cao cấp","full nội thất cao cấp","liền tường cao cấp",
                "hạng sang","luxury","nhập khẩu","châu âu","hafele",
                "kohler","grohe","marriott","5 sao","5*",
                "tặng toàn bộ nội thất cao cấp","bàn giao cao cấp",
                "nội thất thiết kế sang trọng","sang trọng bậc nhất",
                "nội thất liền tường","nội thất dính tường",
                "tiêu chuẩn khách sạn","smarthome","smart home","vsmart",
                "sàn lót đá marble","sàn lát đá marble",
                "đầy đủ","day du","full","nội thất đầy đủ","full nội thất",
                "full nt","fullnội thất","có nội thất","có sẵn nội thất",
                "sẵn nội thất","tặng nội thất","nội thất full",
                "hoàn thiện nội thất","nội thất hoàn thiện","gần full",
                "bán full","đầy đủ tiện nghi","đã trang bị","được trang bị",
                "trang bị nội thất","nội thất hiện đại","nội thất đẹp",
                "chủ để lại","tặng kèm nội thất","nhà đầy đủ nội thất",
                "máy lạnh","điều hòa","tủ lạnh","bếp","rèm","giường",
                "noi that","chủ đầu tư bàn giao","bàn giao theo cdt",
                "bàn giao nội thất","nội thất bàn giao","nội thất cđt",
                "nguyên bản cđt","bàn giao theo tiêu chuẩn","bàn giao chuẩn",
                "nội thất chủ đầu tư","trang bị nội thất chủ đầu tư"]
    CO_BAN   = ["cơ bản","co ban","nội thất cơ bản","hoàn thiện cơ bản",
                "bàn giao cơ bản","noi that co ban","ntcb","căn bản",
                "bàn giao full nội thất cơ bản","nội thất cơ bản từ chủ"]

    # Thu tu: khong nt → co ban → day du
    # (co ban truoc day du vi "hoàn thiện cơ bản full nội thất" → Cơ bản)
    if any(k in v for k in KHONG_NT): return "Không nội thất"
    if any(k in v for k in CO_BAN):   return "Cơ bản"
    if any(k in v for k in DAY_DU):   return "Đầy đủ"
    return None


df["furniture_status_norm"] = df["furniture_status"].apply(rule_furniture)

total      = len(df)
identified = df["furniture_status_norm"].notna().sum()
need_groq  = df["furniture_status_norm"].isna().sum()

print("KET QUA - furniture_status_norm")
print(f"  {'Rule xac dinh':<25} {identified:>7,}  ({identified/total*100:.1f}%)")
print(f"  {'None → giao Groq':<25} {need_groq:>7,}  ({need_groq/total*100:.1f}%)")
print(f"\n  {'Nhan':<20} {'Dong':>8} {'%':>7}")
print("  " + "-" * 38)
for lbl, cnt in df["furniture_status_norm"].value_counts(dropna=False).items():
    label = "(None → Groq)" if pd.isna(lbl) else str(lbl)
    print(f"  {label:<20} {cnt:>8,} {cnt/total*100:>6.1f}%")
# --- Kết quả ---
print("KET QUA - Rule-based Normalization")
for col_norm, col_raw in COL_PAIRS:
    total      = len(df)
    identified = df[col_norm].notna().sum()
    need_groq  = df[col_norm].isna().sum()
    print(f"\n  [{col_raw}] → {col_norm}")
    print(f"  {'Rule xac dinh':<25} {identified:>7,}  ({identified/total*100:.1f}%)")
    print(f"  {'None → giao Groq':<25} {need_groq:>7,}  ({need_groq/total*100:.1f}%)")
    dist = df[col_norm].value_counts()
    for lbl, cnt in dist.items():
        print(f"    {str(lbl):<25} {cnt:>7,}  ({cnt/total*100:.1f}%)")

"""## CELL 9 – Groq fill (có checkpoint)"""

# Chạy cell này nếu runtime bị restart
import pandas as pd, os

TEMP_OUTPUT = os.path.join(OUTPUT_DIR, "data_normalized_temp.csv")
df = pd.read_csv(TEMP_OUTPUT)

# Ép lại datetime
for col in ["posted_at", "expired_at", "snapshot_date"]:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], format="mixed", errors="coerce")

print(f"Da khoi phuc: {df.shape[0]:,} dong")
print(f"Cac cot norm hien tai:")
for col in ["direction_norm","legal_status_norm","furniture_status_norm"]:
    if col in df.columns:
        none_cnt = df[col].isna().sum()
        print(f"  {col}: {none_cnt:,} None con lai")

GROQ_MODEL        = "llama-3.3-70b-versatile"
BATCH_SIZE        = 10
SLEEP_BETWEEN     = 2.2
GROQ_FALLBACK     = "Chưa rõ"
CHECKPOINT_FILE   = os.path.join(OUTPUT_DIR, "checkpoint.json")
TEMP_OUTPUT       = os.path.join(OUTPUT_DIR, "data_normalized_temp.csv")

client = Groq(api_key=GROQ_API_KEY)

def _safe_str(val, max_chars=400):
    return "" if pd.isna(val) else str(val).strip()[:max_chars]

def _build_prompt(rows):
    blocks = []
    for r in rows:
        field_lines = "\n".join(f'    - {c}: "{v}"' for c,v in r["fields"].items())
        blocks.append(
            f'--- ROW {r["row_id"]} ---\n'
            f'  Tiêu đề: {r["title"]}\n'
            f'  Mô tả  : {r["desc"]}\n'
            f'  Cần điền:\n{field_lines}'
        )
    return f"""Chuẩn hóa dữ liệu bất động sản. Dựa vào tiêu đề và mô tả để điền.
Nhãn hợp lệ:
- direction       : {VALID_DIRECTION}
- legal_status    : {VALID_LEGAL}
- furniture_status: {VALID_FURNITURE}
Nếu không đề cập → "{GROQ_FALLBACK}". Chỉ trả JSON array, không giải thích.
Format: [{{"row_id":<số>,"direction":<nhãn>,"legal_status":<nhãn>,"furniture_status":<nhãn>}}]
Dữ liệu:
{"".join(blocks)}"""

def _call_groq(rows):
    for attempt in range(3):
        try:
            resp = client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[{"role":"user","content":_build_prompt(rows)}],
                temperature=0, max_tokens=1024,
            )
            raw = re.sub(r"^```json|^```|```$","", resp.choices[0].message.content.strip(), flags=re.MULTILINE).strip()
            return {r["row_id"]: r for r in json.loads(raw)}
        except Exception as e:
            print(f"   [attempt {attempt+1}/3]  {e}")
            time.sleep(2**attempt)
    return {}

# Load checkpoint
ck = {"batches_done":0}
if os.path.exists(CHECKPOINT_FILE):
    with open(CHECKPOINT_FILE) as f: ck = json.load(f)
    print(f"  Resume từ batch {ck['batches_done']} (lúc {ck.get('timestamp','?')})")
    if os.path.exists(TEMP_OUTPUT):
        temp = pd.read_csv(TEMP_OUTPUT)
        for col_norm,_ in COL_PAIRS:
            if col_norm in temp.columns:
                df[col_norm] = temp[col_norm].values

# Collect rows cần fill
need_mask = pd.Series(False, index=df.index)
for col_norm,_ in COL_PAIRS:
    need_mask |= df[col_norm].isna()
need_idx = df[need_mask].index.tolist()

print(f"\n Groq fill: {len(need_idx):,} rows cần xử lý")

batches = [need_idx[i:i+BATCH_SIZE] for i in range(0, len(need_idx), BATCH_SIZE)]
start   = ck["batches_done"]

for b_num, b_idx in enumerate(batches):
    if b_num < start: continue
    rows_payload = []
    for idx in b_idx:
        fields = {}
        for col_norm, col_raw in COL_PAIRS:
            if pd.isna(df.at[idx, col_norm]):
                fields[col_raw] = _safe_str(df.at[idx, col_raw] if col_raw in df.columns else "")
        if not fields: continue
        rows_payload.append({
            "row_id": int(idx),
            "title" : _safe_str(df.at[idx,"title"]) if "title" in df.columns else "",
            "desc"  : _safe_str(df.at[idx,"listing_description"], 600) if "listing_description" in df.columns else "",
            "fields": fields,
        })

    results = _call_groq(rows_payload)
    filled  = 0
    for idx in b_idx:
        row_r = results.get(int(idx), {})
        for col_norm, col_raw in COL_PAIRS:
            if pd.isna(df.at[idx, col_norm]):
                v = row_r.get(col_raw)
                df.at[idx, col_norm] = v if (v and v != "null") else GROQ_FALLBACK
                filled += 1

    ck = {"batches_done": b_num+1, "timestamp": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")}
    with open(CHECKPOINT_FILE,"w") as f: json.dump(ck,f)
    df.to_csv(TEMP_OUTPUT, index=False)
    print(f"  Batch {b_num+1}/{len(batches)}: điền {filled} ô   temp saved")
    time.sleep(SLEEP_BETWEEN)

# Safety net
for col_norm,_ in COL_PAIRS:
    df[col_norm].fillna(GROQ_FALLBACK, inplace=True)

# --- Kết quả ---
print("\n KẾT QUẢ – Groq Fill")
for col_norm, col_raw in COL_PAIRS:
    total = len(df)
    print(f"\n  [{col_norm}]")
    print(f"  {'Nhãn':<25} {'Dòng':>8} {'%':>7}")
    print("  " + "-"*42)
    for lbl, cnt in df[col_norm].value_counts().items():
        print(f"  {str(lbl):<25} {cnt:>8,} {cnt/total*100:>6.1f}%")

"""## CELL 10 – Verify Groq bằng rule-based"""

rule_funcs  = {"direction_norm"       : rule_direction,
               "legal_status_norm"    : rule_legal,
               "furniture_status_norm": rule_furniture}
col_raw_map = {cn: cr for cn, cr in COL_PAIRS}

conflicts      = []
total_verified = 0
total_conflict = 0
total_skip     = 0

for col_norm, rule_fn in rule_funcs.items():
    col_raw = col_raw_map[col_norm]
    if col_norm not in df.columns or col_raw not in df.columns:
        continue

    for idx in df.index:
        groq_val = df.at[idx, col_norm]
        raw_val  = df.at[idx, col_raw]

        # Neu col_norm van con trong → fill Chua ro
        if pd.isna(groq_val) or str(groq_val).strip() == "":
            df.at[idx, col_norm] = "Chưa rõ"
            continue

        rule_val = rule_fn(raw_val)

        # Rule khong nhan ra → tin Groq, skip
        if rule_val is None:
            total_skip += 1
            continue

        total_verified += 1

        if rule_val != groq_val:
            total_conflict += 1
            conflicts.append({
                "index"    : idx,
                "column"   : col_norm,
                "raw_value": raw_val,
                "groq_fill": groq_val,
                "rule_says": rule_val,
            })
            df.at[idx, col_norm] = rule_val   # override bang rule

conflict_df = pd.DataFrame(conflicts) if conflicts else pd.DataFrame(
    columns=["index","column","raw_value","groq_fill","rule_says"])

# Safety net: dam bao khong con NaN
for col_norm, _ in COL_PAIRS:
    remaining = df[col_norm].isna().sum()
    if remaining > 0:
        df[col_norm].fillna("Chưa rõ", inplace=True)
        print(f"  Safety net: {remaining} NaN con lai [{col_norm}] → 'Chua ro'")

# Ket qua
print("KET QUA - Verify Groq vs Rule-based")
print(f"  {'Tong verify duoc':<25} {total_verified:,}")
print(f"  {'Skip (rule=None)':<25} {total_skip:,}")
print(f"  {'Conflict override':<25} {total_conflict:,}")
if total_verified > 0:
    acc = (total_verified - total_conflict) / total_verified * 100
    print(f"\n  Do chinh xac Groq: {acc:.1f}%  ({total_verified - total_conflict}/{total_verified})")

if not conflict_df.empty:
    path = os.path.join(OUTPUT_DIR, "groq_conflict_report.csv")
    conflict_df.to_csv(path, index=False)
    print(f"\n  Chi tiet conflict ({total_conflict} dong) → {path}")
    print(f"\n  {'Index':>6} {'Cot':<25} {'Raw':<20} {'Groq':<20} {'Rule':>15}")
    print("  " + "-" * 90)
    for _, r in conflict_df.iterrows():
        print(f"  {r['index']:>6} {r['column']:<25} {str(r['raw_value']):<20} "
              f"{str(r['groq_fill']):<20} {str(r['rule_says']):>15}")
else:
    print("\n  Khong co conflict!")

print("\nPhan phoi nhan cuoi:")
for col_norm, _ in COL_PAIRS:
    total = len(df)
    print(f"\n  [{col_norm}]")
    print(f"  {'Nhan':<25} {'Dong':>8} {'%':>7}")
    print("  " + "-" * 42)
    for lbl, cnt in df[col_norm].value_counts(dropna=False).items():
        label = "(NaN)" if pd.isna(lbl) else str(lbl)
        print(f"  {label:<25} {cnt:>8,} {cnt/total*100:>6.1f}%")

"""## CELL 11 – Lưu kết quả cuối"""

FINAL_OUTPUT = os.path.join(OUTPUT_DIR, "data_final_procecessed.csv")
df.to_csv(FINAL_OUTPUT, index=False)

print(f" Đã lưu: {FINAL_OUTPUT}")
print(f"   {len(df):,} dòng × {df.shape[1]} cột")
print(f"   NaN còn lại: {df.isna().sum().sum():,}")

df.info()

for col_norm, col_raw in COL_PAIRS:
    # Chi fill nhung o trong o col_raw
    mask_empty = df[col_raw].isna() | (df[col_raw].str.strip() == "")
    df.loc[mask_empty, col_raw] = df.loc[mask_empty, col_norm]

# Ket qua
print("KET QUA - Gop norm vao cot goc")
print("=" * 55)
for col_norm, col_raw in COL_PAIRS:
    print(f"\n[{col_raw}]")
    print(f"  {'Nhan':<25} {'Dong':>8} {'%':>7}")
    print("  " + "-" * 42)
    for lbl, cnt in df[col_raw].value_counts(dropna=False).items():
        label = "(NaN)" if pd.isna(lbl) else str(lbl)
        print(f"  {label:<25} {cnt:>8,} {cnt/len(df)*100:>6.1f}%")